import { defineConfig } from "tsdown";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "main/index": "src/main/index.ts",
    "main/fs": "src/main/fs/index.ts",
    "main/path": "src/main/path/index.ts",
    "main/app": "src/main/app/index.ts",
    "main/auto-updater": "src/main/auto-updater/index.ts",
    "main/dialog": "src/main/dialog/index.ts",
    "main/global-shortcut": "src/main/global-shortcut/index.ts",
    "main/menu": "src/main/menu/index.ts",
    "main/power-monitor": "src/main/power-monitor/index.ts",
    "main/power-save-blocker": "src/main/power-save-blocker/index.ts",
    "main/push-notifications": "src/main/push-notifications/index.ts",
    "main/safe-storage": "src/main/safe-storage/index.ts",
    "main/session": "src/main/session/index.ts",
    "main/screen": "src/main/screen/index.ts",
    "main/share-menu": "src/main/share-menu/index.ts",
    "main/shell": "src/main/shell/index.ts",
    "main/tray": "src/main/tray/index.ts",
    "main/notification": "src/main/notification/index.ts",
    "main/system-preferences": "src/main/system-preferences/index.ts",
    "main/browserWindow": "src/main/browserWindow/index.ts",
    "renderer/index": "src/renderer/index.ts",
    "renderer/fs": "src/renderer/fs/index.ts",
    "renderer/path": "src/renderer/path/index.ts",
    "renderer/app": "src/renderer/app/index.ts",
    "renderer/auto-updater": "src/renderer/auto-updater/index.ts",
    "renderer/dialog": "src/renderer/dialog/index.ts",
    "renderer/global-shortcut": "src/renderer/global-shortcut/index.ts",
    "renderer/menu": "src/renderer/menu/index.ts",
    "renderer/power-monitor": "src/renderer/power-monitor/index.ts",
    "renderer/power-save-blocker": "src/renderer/power-save-blocker/index.ts",
    "renderer/push-notifications": "src/renderer/push-notifications/index.ts",
    "renderer/safe-storage": "src/renderer/safe-storage/index.ts",
    "renderer/session": "src/renderer/session/index.ts",
    "renderer/screen": "src/renderer/screen/index.ts",
    "renderer/share-menu": "src/renderer/share-menu/index.ts",
    "renderer/shell": "src/renderer/shell/index.ts",
    "renderer/tray": "src/renderer/tray/index.ts",
    "renderer/notification": "src/renderer/notification/index.ts",
    "renderer/system-preferences": "src/renderer/system-preferences/index.ts",
    "renderer/browserWindow": "src/renderer/browserWindow/index.ts",
  },
  format: "esm",
  target: "node22",
  dts: true,
  clean: true,
});
